### ISSUE TITLE
So this works without drawing regions and just with text defining ?

### ISSUE THREAD

**Issue by FurkanGozukara** [NJU-PCALab/RAG-Diffusion#2]
Am I accurate? if so this is revolutionary

**Comment by ZNan-Chen** [comment]
Are you referring to the image repainting part? Currently, image repainting still requires a corresponding mask for the target region. However, your suggestion is insightful! We will consider exploring the possibility of defining regions entirely through text in our future research.

**Comment by FurkanGozukara** [comment]
@ZNan-Chen i am referring to regional prompting alike

i mean like this one

On the left, a penguin wearing sunglasses is sunbathing in the desert; in the center, a tiger wearing a scarf is standing on a glacier; on the right, a panda in a windbreaker is walking through the forest.

![image](https://github.com/user-attachments/assets/db7aed15-ae3d-4ea0-9a6e-d66d811ffafa)

regional prompting was like this but with your case we just give text not mask right?

![image](https://github.com/user-attachments/assets/5cfdd4b3-c0e0-4d87-a58f-fdfcc948dee5)

**Comment by kevincao8828** [comment]
> Are you referring to the image repainting part? Currently, image repainting still requires a corresponding mask for the target region. However, your suggestion is insightful! We will consider exploring the possibility of defining regions entirely through text in our future research.

Is there a quick demo code for repainting? it could take original image and mask as input. Thanks
