### ISSUE TITLE
Feature Request: Is a port to ComfyUI in the works?

### ISSUE THREAD

**Issue by formulake** [NJU-PCALab/RAG-Diffusion#3]
I've been itching to give this a go. It's the most exciting thing since Flux Dev! The results look quite unbelievable and I echo the sentiment of another poster who queried about the possibility of masking being handled by segmentation tools, specifically for inpainting or image editing jobs. But the big question is - **is there any way this can find its way to ComfyUI?** It's an explosive addition to the power of Flux.

**Comment by ZNan-Chen** [comment]
@formulake There are developers working on porting this to ComfyUI. If the progress goes smoothly and it’s completed, I’ll notify you as soon as possible. Thank you for your interest.

**Comment by Lalimec** [comment]
Any progress?
