### ISSUE TITLE
Can you provide a repaint demo?

### ISSUE THREAD

**Issue by kevincao8828** [NJU-PCALab/RAG-Diffusion#4]
Thanks a lot for the great project. I tried to find a way to generate a repaint picture like the ones you posted in the README, but nothing found. Can you provide a repaint demo code?
Thanks again!

**Comment by ZNan-Chen** [comment]
@kevincao8828 We will update the code for image repainting within two weeks. Please stay tuned.

**Comment by kevincao8828** [comment]
Thanks, looking forward to it

**Comment by jesusmartinoza** [comment]
Great work! Also interested in the inpaint demo

**Comment by WalkingwithAI** [comment]
Great job!
