### ISSUE TITLE
分布式训练

### ISSUE THREAD

**Issue by fxyfengxiaoyi** [NJU-PCALab/RAG-Diffusion#5]
感谢您出色的工作，我尝试使用模型进行图片生成，但出现了显存不足的问题，我使用的是单张3090，请问这是正常的吗，如果是正常的，我能否使用三张3090进行分布式的图片生成，希望您可以给我一些帮助，非常感谢！
https://github.com/issues

**Comment by ZNan-Chen** [comment]
@fxyfengxiaoyi 您好，我们的方法无需训练，您可以使用fp8等方案来进行推理，并启用CPU_offloading来降低显存占用.
