### ISSUE TITLE
Does it work on black-forest-labs/FLUX.1-schnell?

### ISSUE THREAD

**Issue by JunbongJang** [NJU-PCALab/RAG-Diffusion#6]
Hi, thank you for your work! 
I wanted to use your method on the faster Flux model.
But when I run your method on black-forest-labs/FLUX.1-schnell, instead of dev, I get this result:

![RAG](https://github.com/user-attachments/assets/24cc3cf2-c833-4fd6-a3a3-8605ce8e7811)

Is your method only for flux-dev version?

**Comment by ZNan-Chen** [comment]
@JunbongJang  RAG is compatible with Flux-Schnell as it doesn't alter the model's structure. However, all our experiments were conducted on Flux-Dev, so you might need to adjust some parameters for optimal results. Here’s an example of the results I achieved using Flux-Schnell.
![RAG](https://github.com/user-attachments/assets/c93b0ae1-d7e5-4cdb-b593-47ab19b0bd93)

    prompt = "a balloon on the bottom of a dog"
    HB_replace = 1
    HB_prompt_list =  [
            "Balloon",
            "Dog"
        ]
    HB_m_offset_list =  [
            0.1,
            0.1
        ]
    HB_n_offset_list =  [
            0.55,
            0.05
        ]
    HB_m_scale_list =  [
            0.8,
            0.8
        ]
    HB_n_scale_list = [
            0.4,
            0.45
        ]
    SR_delta = 0.5
    SR_hw_split_ratio = "0.5; 0.5"
    SR_prompt = "A playful dog, perhaps a golden retriever, with its ears perked up, sitting on the balloon, giving an enthusiastic demeanor. BREAK A colorful balloon floating gently, its string dangling gracefully, just beneath the dog."
    height, width = 1024, 1024
    seed = 7
