### ISSUE TITLE
Sharing VQAScore and GenAI-Bench!

### ISSUE THREAD

**Issue by linzhiqiu** [NJU-PCALab/RAG-Diffusion#7]
Hey,

This is Zhiqiu Lin, a final-year PhD student at Carnegie Mellon University working with Prof. Deva Ramanan. I came across your work and was impressed by the results!

I also wanted to advertise our recent work in collaboration with Meta's GenAI team on the automated evaluation of text-to-visual generative models, which might be of interest to you:

1. [VQAScore](https://linzhiqiu.github.io/papers/vqascore/): We propose a simple but effective automated metric that measures the prompt alignment of generated imagery. VQAScore strongly agrees with human judgments and can be run using one-line Python code [here](https://github.com/linzhiqiu/t2v_metrics)! It also significantly outperforms previous automated metrics such as ImageReward, HPSv2, and PickScore.

2. [GenAI-Bench](https://linzhiqiu.github.io/papers/genai_bench/): We introduce a comprehensive benchmark for compositional image generation (including skills such as spatial relations) with 1,600 prompts written by professional designers. We also show that VQAScore can be used as a strong reward metric by simply reranking the generated candidate images of DALL-E3 or SD-XL. GenAI-Bench was presented as the Best Short Paper at [SynData@CVPR24 workshop](https://syndata4cv.github.io/). 

Best,
Zhiqiu

**Comment by ZNan-Chen** [comment]
@linzhiqiu Hi, Zhiqiu, thank you for sharing these impressive works. We will look into VQAScore and GenAI-Bench and plan to incorporate them into our future experiments for a more comprehensive evaluation. Looking forward to your future research.
